// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ref_read_pmf
NumericMatrix ref_read_pmf(IntegerMatrix Tm, IntegerMatrix Rm, IntegerMatrix Gn, SEXP pldy, SEXP err);
RcppExport SEXP polyfreqs_ref_read_pmf(SEXP TmSEXP, SEXP RmSEXP, SEXP GnSEXP, SEXP pldySEXP, SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Rm(RmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Gn(GnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pldy(pldySEXP);
    Rcpp::traits::input_parameter< SEXP >::type err(errSEXP);
    rcpp_result_gen = Rcpp::wrap(ref_read_pmf(Tm, Rm, Gn, pldy, err));
    return rcpp_result_gen;
END_RCPP
}
// sample_g
IntegerMatrix sample_g(IntegerMatrix Tm, IntegerMatrix Rm, IntegerMatrix Gn, NumericVector pV, SEXP pldy, SEXP err);
RcppExport SEXP polyfreqs_sample_g(SEXP TmSEXP, SEXP RmSEXP, SEXP GnSEXP, SEXP pVSEXP, SEXP pldySEXP, SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Rm(RmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Gn(GnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pV(pVSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pldy(pldySEXP);
    Rcpp::traits::input_parameter< SEXP >::type err(errSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_g(Tm, Rm, Gn, pV, pldy, err));
    return rcpp_result_gen;
END_RCPP
}
// sample_p
NumericVector sample_p(IntegerMatrix Tm, IntegerMatrix Gn, SEXP pldy);
RcppExport SEXP polyfreqs_sample_p(SEXP TmSEXP, SEXP GnSEXP, SEXP pldySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Gn(GnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pldy(pldySEXP);
    rcpp_result_gen = Rcpp::wrap(sample_p(Tm, Gn, pldy));
    return rcpp_result_gen;
END_RCPP
}
// sim_ref_reads
IntegerMatrix sim_ref_reads(IntegerMatrix Tm, IntegerMatrix Gn, SEXP pldy, SEXP err);
RcppExport SEXP polyfreqs_sim_ref_reads(SEXP TmSEXP, SEXP GnSEXP, SEXP pldySEXP, SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Gn(GnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pldy(pldySEXP);
    Rcpp::traits::input_parameter< SEXP >::type err(errSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_ref_reads(Tm, Gn, pldy, err));
    return rcpp_result_gen;
END_RCPP
}
