// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ref_read_pmf
NumericMatrix ref_read_pmf(IntegerMatrix Tm, IntegerMatrix Rm, IntegerMatrix Gn, SEXP pldy, SEXP err);
RcppExport SEXP polyfreqs_ref_read_pmf(SEXP TmSEXP, SEXP RmSEXP, SEXP GnSEXP, SEXP pldySEXP, SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Rm(RmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Gn(GnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pldy(pldySEXP);
    Rcpp::traits::input_parameter< SEXP >::type err(errSEXP);
    __result = Rcpp::wrap(ref_read_pmf(Tm, Rm, Gn, pldy, err));
    return __result;
END_RCPP
}
// csample_integer
IntegerVector csample_integer(IntegerVector x, int size, bool replace, NumericVector prob);
RcppExport SEXP polyfreqs_csample_integer(SEXP xSEXP, SEXP sizeSEXP, SEXP replaceSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type replace(replaceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    __result = Rcpp::wrap(csample_integer(x, size, replace, prob));
    return __result;
END_RCPP
}
// sample_g
IntegerMatrix sample_g(IntegerMatrix Tm, IntegerMatrix Rm, IntegerMatrix Gn, NumericVector pV, SEXP pldy, SEXP err);
RcppExport SEXP polyfreqs_sample_g(SEXP TmSEXP, SEXP RmSEXP, SEXP GnSEXP, SEXP pVSEXP, SEXP pldySEXP, SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Rm(RmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Gn(GnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pV(pVSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pldy(pldySEXP);
    Rcpp::traits::input_parameter< SEXP >::type err(errSEXP);
    __result = Rcpp::wrap(sample_g(Tm, Rm, Gn, pV, pldy, err));
    return __result;
END_RCPP
}
// sample_p
NumericVector sample_p(IntegerMatrix Tm, IntegerMatrix Gn, SEXP pldy);
RcppExport SEXP polyfreqs_sample_p(SEXP TmSEXP, SEXP GnSEXP, SEXP pldySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Gn(GnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pldy(pldySEXP);
    __result = Rcpp::wrap(sample_p(Tm, Gn, pldy));
    return __result;
END_RCPP
}
// sim_ref_reads
IntegerMatrix sim_ref_reads(IntegerMatrix Tm, IntegerMatrix Gn, SEXP pldy, SEXP err);
RcppExport SEXP polyfreqs_sim_ref_reads(SEXP TmSEXP, SEXP GnSEXP, SEXP pldySEXP, SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type Gn(GnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pldy(pldySEXP);
    Rcpp::traits::input_parameter< SEXP >::type err(errSEXP);
    __result = Rcpp::wrap(sim_ref_reads(Tm, Gn, pldy, err));
    return __result;
END_RCPP
}
