# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csample_integer <- function(x, size, replace, prob = as.numeric( c())) {
    .Call('polyfreqs_csample_integer', PACKAGE = 'polyfreqs', x, size, replace, prob)
}

sample_g <- function(Tm, Rm, Gn, pV, pldy, err) {
    .Call('polyfreqs_sample_g', PACKAGE = 'polyfreqs', Tm, Rm, Gn, pV, pldy, err)
}

sample_p <- function(Tm, Gn, pldy) {
    .Call('polyfreqs_sample_p', PACKAGE = 'polyfreqs', Tm, Gn, pldy)
}

